// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "dartjni.h"
#include "jni.h"

thread_local JNIEnv* jniEnv;
JniContext* jni;

JniContext* (*context_getter)(void);
JNIEnv* (*env_getter)(void);

void setJniGetters(JniContext* (*cg)(void), JNIEnv* (*eg)(void)) {
  context_getter = cg;
  env_getter = eg;
}

// de.yugata.editor.audio.AudioAnalyser
jclass _c_AudioAnalyser = NULL;

jmethodID _m_AudioAnalyser__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult AudioAnalyser__new0() {
  load_env();
  load_class_global_ref(&_c_AudioAnalyser,
                        "de/yugata/editor/audio/AudioAnalyser");
  if (_c_AudioAnalyser == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_AudioAnalyser, &_m_AudioAnalyser__new0, "<init>", "()V");
  if (_m_AudioAnalyser__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result =
      (*jniEnv)->NewObject(jniEnv, _c_AudioAnalyser, _m_AudioAnalyser__new0);
  return to_global_ref_result(_result);
}

jmethodID _m_AudioAnalyser__analyseBeats = NULL;
FFI_PLUGIN_EXPORT
JniResult AudioAnalyser__analyseBeats(jobject audioInput,
                                      double peakThreshold,
                                      double msThreshold) {
  load_env();
  load_class_global_ref(&_c_AudioAnalyser,
                        "de/yugata/editor/audio/AudioAnalyser");
  if (_c_AudioAnalyser == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_static_method(_c_AudioAnalyser, &_m_AudioAnalyser__analyseBeats,
                     "analyseBeats", "(Ljava/lang/String;DD)Ljava/util/List;");
  if (_m_AudioAnalyser__analyseBeats == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->CallStaticObjectMethod(
      jniEnv, _c_AudioAnalyser, _m_AudioAnalyser__analyseBeats, audioInput,
      peakThreshold, msThreshold);
  return to_global_ref_result(_result);
}

jmethodID _m_AudioAnalyser__analyseStamps = NULL;
FFI_PLUGIN_EXPORT
JniResult AudioAnalyser__analyseStamps(jobject audioInput,
                                       double peakThreshold,
                                       double msThreshold) {
  load_env();
  load_class_global_ref(&_c_AudioAnalyser,
                        "de/yugata/editor/audio/AudioAnalyser");
  if (_c_AudioAnalyser == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_static_method(_c_AudioAnalyser, &_m_AudioAnalyser__analyseStamps,
                     "analyseStamps", "(Ljava/lang/String;DD)Ljava/util/List;");
  if (_m_AudioAnalyser__analyseStamps == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->CallStaticObjectMethod(
      jniEnv, _c_AudioAnalyser, _m_AudioAnalyser__analyseStamps, audioInput,
      peakThreshold, msThreshold);
  return to_global_ref_result(_result);
}

jmethodID _m_AudioAnalyser__analyseBeats1 = NULL;
FFI_PLUGIN_EXPORT
JniResult AudioAnalyser__analyseBeats1(jobject audioInput,
                                       double peakThreshold,
                                       double msThreshold,
                                       jobject tracker) {
  load_env();
  load_class_global_ref(&_c_AudioAnalyser,
                        "de/yugata/editor/audio/AudioAnalyser");
  if (_c_AudioAnalyser == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_static_method(
      _c_AudioAnalyser, &_m_AudioAnalyser__analyseBeats1, "analyseBeats",
      "(Ljava/lang/String;DDLbe/tarsos/dsp/onsets/OnsetHandler;)V");
  if (_m_AudioAnalyser__analyseBeats1 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_AudioAnalyser,
                                  _m_AudioAnalyser__analyseBeats1, audioInput,
                                  peakThreshold, msThreshold, tracker);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// de.yugata.editor.editor.EditorWrapper
jclass _c_EditorWrapper = NULL;

jmethodID _m_EditorWrapper__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult EditorWrapper__new0() {
  load_env();
  load_class_global_ref(&_c_EditorWrapper,
                        "de/yugata/editor/editor/EditorWrapper");
  if (_c_EditorWrapper == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_EditorWrapper, &_m_EditorWrapper__new0, "<init>", "()V");
  if (_m_EditorWrapper__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result =
      (*jniEnv)->NewObject(jniEnv, _c_EditorWrapper, _m_EditorWrapper__new0);
  return to_global_ref_result(_result);
}

jmethodID _m_EditorWrapper__edit = NULL;
FFI_PLUGIN_EXPORT
JniResult EditorWrapper__edit(jobject json, uint8_t useSegments) {
  load_env();
  load_class_global_ref(&_c_EditorWrapper,
                        "de/yugata/editor/editor/EditorWrapper");
  if (_c_EditorWrapper == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_static_method(_c_EditorWrapper, &_m_EditorWrapper__edit, "edit",
                     "(Ljava/lang/String;Z)V");
  if (_m_EditorWrapper__edit == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallStaticVoidMethod(jniEnv, _c_EditorWrapper,
                                  _m_EditorWrapper__edit, json, useSegments);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}
