// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: file_names
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_cast
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name

import "dart:isolate" show ReceivePort;
import "dart:ffi" as ffi;
import "package:jni/internal_helpers_for_jnigen.dart";
import "package:jni/jni.dart" as jni;

// Auto-generated initialization code.

final ffi.Pointer<T> Function<T extends ffi.NativeType>(String sym) jniLookup =
    ProtectedJniExtensions.initGeneratedLibrary("tarsosDSP");

/// from: de.yugata.audio.AudioAnalyser
class AudioAnalyser extends jni.JObject {
  @override
  late final jni.JObjType<AudioAnalyser> $type = type;

  AudioAnalyser.fromRef(
    jni.JObjectPtr ref,
  ) : super.fromRef(ref);

  /// The type which includes information such as the signature of this class.
  static const type = $AudioAnalyserType();
  static final _new0 = jniLookup<ffi.NativeFunction<jni.JniResult Function()>>(
          "AudioAnalyser__new0")
      .asFunction<jni.JniResult Function()>();

  /// from: public void <init>()
  /// The returned object must be released after use, by calling the [release] method.
  factory AudioAnalyser() {
    return AudioAnalyser.fromRef(_new0().object);
  }

  static final _analyseBeats = jniLookup<
          ffi.NativeFunction<
              jni.JniResult Function(ffi.Pointer<ffi.Void>, ffi.Double,
                  ffi.Double)>>("AudioAnalyser__analyseBeats")
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, double, double)>();

  /// from: static public java.util.List<java.lang.Double> analyseBeats(java.lang.String audioInput, double peakThreshold, double msThreshold)
  /// The returned object must be released after use, by calling the [release] method.
  static jni.JList<jni.JDouble> analyseBeats(
    jni.JString audioInput,
    double peakThreshold,
    double msThreshold,
  ) {
    return const jni.JListType(jni.JDoubleType()).fromRef(
        _analyseBeats(audioInput.reference, peakThreshold, msThreshold).object);
  }

  static final _analyseStamps = jniLookup<
          ffi.NativeFunction<
              jni.JniResult Function(ffi.Pointer<ffi.Void>, ffi.Double,
                  ffi.Double)>>("AudioAnalyser__analyseStamps")
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, double, double)>();

  /// from: static public java.util.List<java.lang.Double> analyseStamps(java.lang.String audioInput, double peakThreshold, double msThreshold)
  /// The returned object must be released after use, by calling the [release] method.
  static jni.JList<jni.JDouble> analyseStamps(
    jni.JString audioInput,
    double peakThreshold,
    double msThreshold,
  ) {
    return const jni.JListType(jni.JDoubleType()).fromRef(
        _analyseStamps(audioInput.reference, peakThreshold, msThreshold)
            .object);
  }

  static final _analyseBeats1 = jniLookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                  ffi.Pointer<ffi.Void>,
                  ffi.Double,
                  ffi.Double,
                  ffi.Pointer<ffi.Void>)>>("AudioAnalyser__analyseBeats1")
      .asFunction<
          jni.JniResult Function(
              ffi.Pointer<ffi.Void>, double, double, ffi.Pointer<ffi.Void>)>();

  /// from: static public void analyseBeats(java.lang.String audioInput, double peakThreshold, double msThreshold, be.tarsos.dsp.onsets.OnsetHandler tracker)
  static void analyseBeats1(
    jni.JString audioInput,
    double peakThreshold,
    double msThreshold,
    jni.JObject tracker,
  ) {
    return _analyseBeats1(
            audioInput.reference, peakThreshold, msThreshold, tracker.reference)
        .check();
  }
}

final class $AudioAnalyserType extends jni.JObjType<AudioAnalyser> {
  const $AudioAnalyserType();

  @override
  String get signature => r"Lde/yugata/audio/AudioAnalyser;";

  @override
  AudioAnalyser fromRef(jni.JObjectPtr ref) => AudioAnalyser.fromRef(ref);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($AudioAnalyserType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($AudioAnalyserType) &&
        other is $AudioAnalyserType;
  }
}
