// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: file_names
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_cast
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name

import "dart:isolate" show ReceivePort;
import "dart:ffi" as ffi;
import "package:jni/internal_helpers_for_jnigen.dart";
import "package:jni/jni.dart" as jni;

// Auto-generated initialization code.

final ffi.Pointer<T> Function<T extends ffi.NativeType>(String sym) jniLookup =
    ProtectedJniExtensions.initGeneratedLibrary("easy_edits");

/// from: de.yugata.easy.edits.audio.AudioAnalyser
class AudioAnalyser extends jni.JObject {
  @override
  late final jni.JObjType<AudioAnalyser> $type = type;

  AudioAnalyser.fromRef(
    jni.JObjectPtr ref,
  ) : super.fromRef(ref);

  /// The type which includes information such as the signature of this class.
  static const type = $AudioAnalyserType();
  static final _new0 = jniLookup<ffi.NativeFunction<jni.JniResult Function()>>(
          "AudioAnalyser__new0")
      .asFunction<jni.JniResult Function()>();

  /// from: public void <init>()
  /// The returned object must be released after use, by calling the [release] method.
  factory AudioAnalyser() {
    return AudioAnalyser.fromRef(_new0().object);
  }

  static final _analyseBeats = jniLookup<
          ffi.NativeFunction<
              jni.JniResult Function(ffi.Pointer<ffi.Void>, ffi.Double,
                  ffi.Double)>>("AudioAnalyser__analyseBeats")
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, double, double)>();

  /// from: static public java.util.List analyseBeats(java.lang.String string, double d, double d1)
  /// The returned object must be released after use, by calling the [release] method.
  static jni.JList<jni.JDouble> analyseBeats(
    jni.JString string,
    double d,
    double d1,
  ) {
    return const jni.JListType(jni.JDoubleType())
        .fromRef(_analyseBeats(string.reference, d, d1).object);
  }

  static final _analyseStamps = jniLookup<
          ffi.NativeFunction<
              jni.JniResult Function(ffi.Pointer<ffi.Void>, ffi.Double,
                  ffi.Double)>>("AudioAnalyser__analyseStamps")
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, double, double)>();

  /// from: static public java.util.List analyseStamps(java.lang.String string, double d, double d1)
  /// The returned object must be released after use, by calling the [release] method.
  static jni.JList<jni.JDouble> analyseStamps(
    jni.JString string,
    double d,
    double d1,
  ) {
    return const jni.JListType(jni.JDoubleType())
        .fromRef(_analyseStamps(string.reference, d, d1).object);
  }

  static final _analyseBeats1 = jniLookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                  ffi.Pointer<ffi.Void>,
                  ffi.Double,
                  ffi.Double,
                  ffi.Pointer<ffi.Void>)>>("AudioAnalyser__analyseBeats1")
      .asFunction<
          jni.JniResult Function(
              ffi.Pointer<ffi.Void>, double, double, ffi.Pointer<ffi.Void>)>();

  /// from: static public void analyseBeats(java.lang.String string, double d, double d1, be.tarsos.dsp.onsets.OnsetHandler onsetHandler)
  static void analyseBeats1(
    jni.JString string,
    double d,
    double d1,
    jni.JObject onsetHandler,
  ) {
    return _analyseBeats1(string.reference, d, d1, onsetHandler.reference)
        .check();
  }
}

final class $AudioAnalyserType extends jni.JObjType<AudioAnalyser> {
  const $AudioAnalyserType();

  @override
  String get signature => r"Lde/yugata/easy/edits/audio/AudioAnalyser;";

  @override
  AudioAnalyser fromRef(jni.JObjectPtr ref) => AudioAnalyser.fromRef(ref);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($AudioAnalyserType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($AudioAnalyserType) &&
        other is $AudioAnalyserType;
  }
}

/// from: de.yugata.easy.edits.editor.FlutterWrapper
class FlutterWrapper extends jni.JObject {
  @override
  late final jni.JObjType<FlutterWrapper> $type = type;

  FlutterWrapper.fromRef(
    jni.JObjectPtr ref,
  ) : super.fromRef(ref);

  /// The type which includes information such as the signature of this class.
  static const type = $FlutterWrapperType();
  static final _new0 = jniLookup<ffi.NativeFunction<jni.JniResult Function()>>(
          "FlutterWrapper__new0")
      .asFunction<jni.JniResult Function()>();

  /// from: public void <init>()
  /// The returned object must be released after use, by calling the [release] method.
  factory FlutterWrapper() {
    return FlutterWrapper.fromRef(_new0().object);
  }

  static final _getFilters =
      jniLookup<ffi.NativeFunction<jni.JniResult Function()>>(
              "FlutterWrapper__getFilters")
          .asFunction<jni.JniResult Function()>();

  /// from: static public java.util.List getFilters()
  /// The returned object must be released after use, by calling the [release] method.
  static jni.JList<FilterWrapper> getFilters() {
    return const jni.JListType($FilterWrapperType())
        .fromRef(_getFilters().object);
  }

  static final _exportSegments = jniLookup<
              ffi
              .NativeFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>>(
          "FlutterWrapper__exportSegments")
      .asFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>();

  /// from: static public void exportSegments(java.lang.String string)
  static void exportSegments(
    jni.JString string,
  ) {
    return _exportSegments(string.reference).check();
  }

  static final _edit = jniLookup<
              ffi
              .NativeFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>>(
          "FlutterWrapper__edit")
      .asFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>();

  /// from: static public void edit(java.lang.String string)
  static void edit(
    jni.JString string,
  ) {
    return _edit(string.reference).check();
  }
}

final class $FlutterWrapperType extends jni.JObjType<FlutterWrapper> {
  const $FlutterWrapperType();

  @override
  String get signature => r"Lde/yugata/easy/edits/editor/FlutterWrapper;";

  @override
  FlutterWrapper fromRef(jni.JObjectPtr ref) => FlutterWrapper.fromRef(ref);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($FlutterWrapperType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($FlutterWrapperType) &&
        other is $FlutterWrapperType;
  }
}

/// from: de.yugata.easy.edits.editor.filter.FilterWrapper
class FilterWrapper extends jni.JObject {
  @override
  late final jni.JObjType<FilterWrapper> $type = type;

  FilterWrapper.fromRef(
    jni.JObjectPtr ref,
  ) : super.fromRef(ref);

  /// The type which includes information such as the signature of this class.
  static const type = $FilterWrapperType();
  static final _new0 = jniLookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<ffi.Void>)>>("FilterWrapper__new0")
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>)>();

  /// from: public void <init>(java.lang.String string, java.lang.String string1, java.util.List list)
  /// The returned object must be released after use, by calling the [release] method.
  factory FilterWrapper(
    jni.JString string,
    jni.JString string1,
    jni.JList<FilterValue> list,
  ) {
    return FilterWrapper.fromRef(
        _new0(string.reference, string1.reference, list.reference).object);
  }

  static final _getName = jniLookup<
              ffi
              .NativeFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>>(
          "FilterWrapper__getName")
      .asFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>();

  /// from: public java.lang.String getName()
  /// The returned object must be released after use, by calling the [release] method.
  jni.JString getName() {
    return const jni.JStringType().fromRef(_getName(reference).object);
  }

  static final _getDescription = jniLookup<
              ffi
              .NativeFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>>(
          "FilterWrapper__getDescription")
      .asFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>();

  /// from: public java.lang.String getDescription()
  /// The returned object must be released after use, by calling the [release] method.
  jni.JString getDescription() {
    return const jni.JStringType().fromRef(_getDescription(reference).object);
  }

  static final _getValues = jniLookup<
              ffi
              .NativeFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>>(
          "FilterWrapper__getValues")
      .asFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>();

  /// from: public java.util.List getValues()
  /// The returned object must be released after use, by calling the [release] method.
  jni.JList<FilterValue> getValues() {
    return const jni.JListType($FilterValueType())
        .fromRef(_getValues(reference).object);
  }
}

final class $FilterWrapperType extends jni.JObjType<FilterWrapper> {
  const $FilterWrapperType();

  @override
  String get signature => r"Lde/yugata/easy/edits/editor/filter/FilterWrapper;";

  @override
  FilterWrapper fromRef(jni.JObjectPtr ref) => FilterWrapper.fromRef(ref);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($FilterWrapperType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($FilterWrapperType) &&
        other is $FilterWrapperType;
  }
}

/// from: de.yugata.easy.edits.editor.filter.FilterValue
class FilterValue extends jni.JObject {
  @override
  late final jni.JObjType<FilterValue> $type = type;

  FilterValue.fromRef(
    jni.JObjectPtr ref,
  ) : super.fromRef(ref);

  /// The type which includes information such as the signature of this class.
  static const type = $FilterValueType();
  static final _new0 = jniLookup<
          ffi.NativeFunction<
              jni.JniResult Function(ffi.Pointer<ffi.Void>,
                  ffi.Pointer<ffi.Void>)>>("FilterValue__new0")
      .asFunction<
          jni.JniResult Function(
              ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>();

  /// from: public void <init>(java.lang.String string, java.lang.String string1)
  /// The returned object must be released after use, by calling the [release] method.
  factory FilterValue(
    jni.JString string,
    jni.JString string1,
  ) {
    return FilterValue.fromRef(
        _new0(string.reference, string1.reference).object);
  }

  static final _getName = jniLookup<
              ffi
              .NativeFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>>(
          "FilterValue__getName")
      .asFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>();

  /// from: public java.lang.String getName()
  /// The returned object must be released after use, by calling the [release] method.
  jni.JString getName() {
    return const jni.JStringType().fromRef(_getName(reference).object);
  }

  static final _getValue = jniLookup<
              ffi
              .NativeFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>>(
          "FilterValue__getValue")
      .asFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>();

  /// from: public java.lang.String getValue()
  /// The returned object must be released after use, by calling the [release] method.
  jni.JString getValue() {
    return const jni.JStringType().fromRef(_getValue(reference).object);
  }
}

final class $FilterValueType extends jni.JObjType<FilterValue> {
  const $FilterValueType();

  @override
  String get signature => r"Lde/yugata/easy/edits/editor/filter/FilterValue;";

  @override
  FilterValue fromRef(jni.JObjectPtr ref) => FilterValue.fromRef(ref);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($FilterValueType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($FilterValueType) && other is $FilterValueType;
  }
}
